server:
  port: 8080

spring:
  application:
    name: vrs-pedidos
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

logging:
  level:
    com.vrsoftware.vrspedidos: DEBUG
    org.springframework.amqp: DEBUG