version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: vrs-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - vrs-network

volumes:
  rabbitmq_data:

networks:
  vrs-network:
    driver: bridge